# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0003_auto_20180131_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntlocation',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
