# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0004_restrauntlocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
