# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0005_auto_20180131_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntlocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
