# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0006_restrauntlocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restrauntlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
