# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0007_auto_20180131_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrauntlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
