# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import restraunts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restraunts', '0008_restrauntlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrauntlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[restraunts.validators.validate_category]),
        ),
    ]
